version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=burgerfast
      - MYSQL_PASSWORD=password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "../docker/mysqldb/initdb.sql:/docker-entrypoint-initdb.d/1.sql"
      - "../docker/mysqldb:/docker/mysql"
  api:
    container_name: api
    image: burgerfast:latest
    environment:
      - DB_URL=mysqldb
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    restart: always

volumes:
  mysqldb:
